spring:
  data:
  datasource:
    url: jdbc:mysql://localhost:3306/eboox
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      pool-name: HikariCP-1
      auto-commit: true
  jpa:
    generate-ddl: true